# GitHub Pages Configuration for SFCC Development MCP Server
title: SFCC Dev MCP Server
description: AI-powered development tools for Salesforce B2C Commerce Cloud
url: "https://taurgis.github.io"
baseurl: "/sfcc-dev-mcp"

# Theme
theme: jekyll-theme-dinky
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - installation.md
  - features.md
  - ai-interfaces.md
  - configuration.md
  - tools.md
  - examples.md
  - security.md
  - troubleshooting.md
  - development.md

# Social links
github_username: taurgis

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections:
  guides:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - node_modules/
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - README.md
