blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/taurgis/sfcc-dev-mcp/blob/main/README.md
    about: Read the project documentation and setup guide
  - name: 🔒 Security Issues
    url: https://github.com/taurgis/sfcc-dev-mcp/security/advisories/new
    about: Report security vulnerabilities privately

